{
 "title": "LANcache",
 "tags": [
  "lancache",
  "nginx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"10.0.20.2:9113\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"10.0.20.2:9113\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{instance=\"10.0.20.2:9113\"}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_accepted{instance=\"10.0.20.2:9113\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"10.0.20.2:9113\"}[5m])",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "connps" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{instance=\"10.0.20.2:9113\"}[5m])",
     "legendFormat": "Connections/s"
    }
   ]
  },
  {
   "title": "Connection States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"10.0.20.2:9113\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "nginx_connections_reading{instance=\"10.0.20.2:9113\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_connections_writing{instance=\"10.0.20.2:9113\"}",
     "legendFormat": "Writing"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"10.0.20.2:9113\"}",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}