{
 "title": "OPNSense Public",
 "description": "OPNSense metrics",
 "tags": [
  "opnsense",
  "public"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"opnsense-glovary\"} - node_boot_time_seconds{job=\"opnsense-glovary\"}"
    }
   ]
  },
  {
   "title": "Net pkts/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{job=\"opnsense-glovary\"}[$__interval]) +  rate(node_network_transmit_packets_total{job=\"opnsense-glovary\"}[$__interval])) > 0"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "description": "Thermal Throttling 100ª",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "🛠️ System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"opnsense-glovary\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"opnsense-glovary\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{job=\"opnsense-glovary\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "🔼 WAN Tx Traffic - Upload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"opnsense-glovary\",device=\"igc1\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔽 WAN Rx Traffic - Download",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"opnsense-glovary\",device=\"igc1\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"opnsense-glovary\"} + node_memory_inactive_bytes{job=\"opnsense-glovary\"}"
    }
   ]
  },
  {
   "title": "🔥 Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{job=\"opnsense-glovary\",cpu=\"0\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{job=\"opnsense-glovary\"} - node_memory_swap_used_bytes{job=\"opnsense-glovary\"}"
    }
   ]
  },
  {
   "title": "📡 WAN In/Out VLAN603",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"opnsense-glovary\",device=\"vlan0.603\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"opnsense-glovary\",device=\"vlan0.603\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "📶Internet traffic per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"opnsense-glovary\",device=\"igc1\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    },
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"opnsense-glovary\",device=\"igc1\"}[60m])",
     "legendFormat": "{{device}}_receive"
    }
   ]
  },
  {
   "title": "📡 WAN In/Out VLAN605",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"opnsense-glovary\",device=\"vlan0.605\"}[$__rate_interval])*8",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"opnsense-glovary\",device=\"vlan0.605\"}[$__rate_interval])*8",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "⚡WAN Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"opnsense-glovary\",device=\"vlan0.603\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"opnsense-glovary\",device=\"vlan0.605\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"opnsense-glovary\",device=\"vlan0.605\"}[1m])",
     "legendFormat": "Transmit: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"opnsense-glovary\",device=\"vlan0.603\"}[1m])",
     "legendFormat": "Transmit: {{ device }}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"opnsense-glovary\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_active_bytes{job=\"opnsense-glovary\"}",
     "legendFormat": "Active (Used)"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"opnsense-glovary\"} + node_memory_buffer_bytes{job=\"opnsense-glovary\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"opnsense-glovary\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_wired_bytes{job=\"opnsense-glovary\"}",
     "legendFormat": "Wired (Kernel)"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_devstat_bytes_total{type=\"write\",device!~\"pass.*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}